# WARNING: no tested
name: tumor-classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
# torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=12.1
  - pip
  - pip:
      - tensorflow
      - keras